version: '3.1'

services:

  web:
    build:
      context: ./django_mysql_docker
      dockerfile: ./Dockerfile
    command:
      bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - mysql-airflow
    restart: always

  adminer-airflow:
    image: adminer
    restart: always
    container_name: adminer-airflow
    depends_on:
      - mysql-airflow
    ports:
      - 9080:8080

  mysql-airflow:
    image: mysql:8.0.19
    restart: always
    container_name: mysql-airflow
    ports:
      - 53306:3306
    volumes:
      - ./mysql_datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "airflow_db"
      MYSQL_USER: "airflow_db_user"
      MYSQL_PASSWORD: "airflow_db_passwd"
      MYSQL_HOST: "mysql-airflow"
    command: "--default-authentication-plugin=mysql_native_password --innodb_buffer_pool_size=1G --innodb_log_file_size=256M --innodb_flush_log_at_trx_commit=1 --innodb_flush_method=O_DIRECT --explicit_defaults_for_timestamp=1"

